version: "3"
services:
	service1:
		container_name: "nginx-container"
		build:
			context: /home/esteban/Desktop/AySO
			dockerfile: Dockerfile
		ports:
			- "80:80"
		restart: always

	service2:
		container_name: "mysql-container"
		image: mysql
		ports:
			- "8080:8080"